name: Run Task Tests

"on":
  pull_request

jobs:
  run-task-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: b2a7270857d061be65129e31a518969100f82e67
          path: test-renovate

      - name: Checkout konflux-ci/konflux-ci Repository
        uses: actions/checkout@v4
        with:
          repository: 'konflux-ci/konflux-ci'
          path: konflux-ci
          ref: b2a7270857d061be65129e31a518969100f82e67
