name: Run Task Tests

"on":
  pull_request

jobs:
  run-task-tests:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: "${{ github.event.pull_request.head.sha }}"
          path: test-renovate

      - name: Checkout konflux-ci/konflux-ci Repository
        uses: actions/checkout@v4
        with:
          repository: 'konflux-ci/konflux-ci'
          path: konflux-ci
          ref: c4630e684e81f71bfd920fff0c9bb2956d3265f4
